
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.zlk.blog.entity


  #pagehelper分页插件
pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql

spring:

  datasource:
            name: test
            url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&amp;characterEncoding=utf-8
            username: root
            password: 123root
            # ʹ阿里druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20


  mail:
      host: smtp.163.com
      username: 15884308429@163.com
      password: zlk1850252892
      properties:
          mail:
              smtp:
                  auth: true
                  timeout: 25000

redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
security:
  oauth2:
    resource:
      filter-order: 3
    sso:
      login-path: /login_page
server:
  port: 80

